export const GENERAL_TYPES = {
  SET_APP_LOADING: 'SET_APP_LOADING',
  RESET_STORE: 'RESET_STORE',
}

export const FX_TYPES = {
  LOADING_FX_RATES: 'LOADING_FX_RATES',
  REQUEST_FX_RATES: 'REQUEST_FX_RATES',
  ONSUCCESS_FX_RATES: 'ONSUCCESS_FX_RATES',
  SET_BASE_CURRENCY: 'SET_BASE_CURRENCY',
  SET_CURRENCIES_PICKED: 'SET_CURRENCIES_PICKED',
}
