export const GENERAL_TYPES = {
  SET_APP_LOADING: 'SET_APP_LOADING',
  RESET_STORE: 'RESET_STORE',
}

export const FX_TYPES = {
  LOADING_FX_RATES: 'LOADING_FX_RATES',
  REQUEST_FX_RATES: 'REQUEST_FX_RATES',
  ONSUCCESS_FX_RATES: 'ONSUCCESS_FX_RATES',
  ON_CURRENCIES_PICKED: 'ON_CURRENCIES_PICKED',
  SET_CURRENCIES_PICKED: 'SET_CURRENCIES_PICKED',
  SUBMIT_TRANSACTION_ENTRY: 'SUBMIT_TRANSACTION_ENTRY',
}

export const CURRENCYNAMES_TYPES = {
  REQUEST_CURRENCIES_NAMES: 'REQUEST_CURRENCIES_NAMES',
  SET_CURRENCIES_NAMES: 'SET_CURRENCIES_NAMES',
}
